### ISSUE TITLE
Unpublished from marketplace

### ISSUE THREAD

**Issue by jakenvac** [ayush-lal/darkly-vscode-theme#1]
I'm unable to install this theme as it is apparently 'unpublished'.
<img width="856" alt="image" src="https://user-images.githubusercontent.com/9119973/163066859-d36b9cbe-337d-4ac9-85ca-5eef1e4bfb40.png">

**Comment by ayush-lal** [comment]
Hey @JakeHL, sorry for the inconvenience, the new theme name is called "Darkly". The previous theme has been deleted however Im unsure why it exists in the market place. I'll continue to look into it and thank you for brining it to my attention. 

**
![image](https://user-images.githubusercontent.com/41420385/163796511-9f79a02e-faa2-400d-a17c-e5f36e1492fb.png)
**

**Comment by jakenvac** [comment]
Ah sorry I should have noticed. Thanks for the clarification!
